import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google'
import Navbar from "./component/header";
import Footer from "./component/footer";
const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight:['200', '300', '400', '500', '600', '700', '800', '900']
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased bg-[url('https://wallpapercave.com/wp/wp2757900.gif')]` 
        }
          >
            <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
